<!DOCTYPE html>
<html>
    <head>
        <title>Oposto</title>           
    </head>
    <body>
       <?php
           $valor1 = 10;
           $valor2 = -15;
           echo "O oposto de valor 1 é " . -$valor1;
           //- na frente de uma variável, valor oposto da mesma
           echo "<br> O oposto de valor 2 é " . -$valor2;
           //ao colocar o sinal - na frente de uma variável,
           //você obtém o valor oposto da mesma
    ?>   
    </body>
</html>
